export type UxCatalogScene = {
  id: string;
  journey: string;
  surface: string;
  state: string;
  expectedSurface: string;
};

export const UX_CATALOG_SCENES: readonly UxCatalogScene[] = [
  { id: "chrome-nav-no-identity", journey: "chrome", surface: "nav", state: "no-identity", expectedSurface: "site-nav" },
  { id: "chrome-nav-needs-enable", journey: "chrome", surface: "nav", state: "needs-enable", expectedSurface: "site-nav" },
  { id: "chrome-nav-enabled", journey: "chrome", surface: "nav", state: "enabled", expectedSurface: "site-nav" },
  { id: "chrome-session-offline", journey: "chrome", surface: "session-banner", state: "offline", expectedSurface: "session-banner" },
  { id: "chrome-tab-lock", journey: "chrome", surface: "tab-lock", state: "locked", expectedSurface: "tab-lock-banner" },
  { id: "welcome-loading", journey: "connect", surface: "welcome", state: "loading", expectedSurface: "welcome-page" },
  { id: "welcome-qr-populated", journey: "connect", surface: "welcome", state: "qr-populated", expectedSurface: "welcome-page" },
  { id: "welcome-expired", journey: "connect", surface: "welcome", state: "expired", expectedSurface: "welcome-page" },
  { id: "welcome-authenticated", journey: "connect", surface: "welcome", state: "authenticated", expectedSurface: "welcome-page" },
  { id: "welcome-adopt-confirm", journey: "connect", surface: "welcome", state: "adopt-confirm", expectedSurface: "welcome-page" },
  { id: "welcome-error", journey: "connect", surface: "welcome", state: "error", expectedSurface: "welcome-page" },
  { id: "enable-checking", journey: "enable", surface: "enable", state: "checking", expectedSurface: "enable-page" },
  { id: "enable-waiting-qr", journey: "enable", surface: "enable", state: "waiting-qr", expectedSurface: "enable-page" },
  { id: "enable-offline", journey: "enable", surface: "enable", state: "offline", expectedSurface: "enable-page" },
  { id: "enable-enabled", journey: "enable", surface: "enable", state: "enabled", expectedSurface: "enable-page" },
  { id: "enable-expired", journey: "enable", surface: "enable", state: "expired", expectedSurface: "enable-page" },
  { id: "enable-error", journey: "enable", surface: "enable", state: "error", expectedSurface: "enable-page" },
  { id: "enable-denied", journey: "enable", surface: "enable", state: "denied", expectedSurface: "enable-page" },
  { id: "chats-loading", journey: "chats", surface: "chats-list", state: "loading", expectedSurface: "chats-page" },
  { id: "chats-empty-enable", journey: "chats", surface: "chats-list", state: "empty-enable", expectedSurface: "chats-page" },
  { id: "chats-empty-candidate", journey: "chats", surface: "chats-list", state: "empty-candidate", expectedSurface: "chats-page" },
  { id: "chats-start-error", journey: "chats", surface: "chats-list", state: "start-error", expectedSurface: "chats-page" },
  { id: "chats-starting-disabled", journey: "chats", surface: "chats-list", state: "starting", expectedSurface: "chats-page" },
  { id: "chats-populated", journey: "chats", surface: "chats-list", state: "populated", expectedSurface: "chats-page" },
  { id: "chats-error", journey: "chats", surface: "chats-list", state: "error", expectedSurface: "chats-page" },
  { id: "thread-empty", journey: "chats", surface: "thread", state: "empty", expectedSurface: "thread-view" },
  { id: "thread-populated", journey: "chats", surface: "thread", state: "populated", expectedSurface: "thread-view" },
  { id: "thread-loading", journey: "chats", surface: "thread", state: "loading", expectedSurface: "thread-view" },
  { id: "thread-sending", journey: "chats", surface: "thread", state: "sending", expectedSurface: "thread-view" },
  { id: "thread-delivery-labels", journey: "chats", surface: "thread", state: "delivery-labels", expectedSurface: "thread-view" },
  { id: "thread-failed-retry", journey: "chats", surface: "thread", state: "failed-retry", expectedSurface: "thread-view" },
  { id: "thread-payment-notice", journey: "payments", surface: "thread", state: "payment-requested", expectedSurface: "thread-view" },
  { id: "thread-payment-proof", journey: "payments", surface: "thread", state: "payment-paid", expectedSurface: "thread-view" },
  { id: "thread-payment-expired", journey: "payments", surface: "thread", state: "payment-expired", expectedSurface: "thread-view" },
  { id: "thread-payment-failed", journey: "payments", surface: "thread", state: "payment-failed", expectedSurface: "thread-view" },
  { id: "thread-payment-unverified", journey: "payments", surface: "thread", state: "payment-unverified", expectedSurface: "thread-view" },
  { id: "thread-disabled-composer", journey: "chats", surface: "thread", state: "disabled-composer", expectedSurface: "thread-view" },
  { id: "requests-empty", journey: "requests", surface: "requests", state: "empty", expectedSurface: "requests-page" },
  { id: "requests-populated", journey: "requests", surface: "requests", state: "populated", expectedSurface: "requests-page" },
  { id: "requests-group-invite", journey: "requests", surface: "requests", state: "group-invite", expectedSurface: "requests-page" },
  { id: "requests-busy", journey: "requests", surface: "requests", state: "busy", expectedSurface: "requests-page" },
  { id: "requests-error", journey: "requests", surface: "requests", state: "error", expectedSurface: "requests-page" },
  { id: "channels-private-empty", journey: "channels", surface: "channels-private", state: "empty", expectedSurface: "channels-page" },
  { id: "channels-private-populated", journey: "channels", surface: "channels-private", state: "populated", expectedSurface: "channels-page" },
  { id: "channels-private-error", journey: "channels", surface: "channels-private", state: "error", expectedSurface: "channels-page" },
  { id: "channels-private-busy", journey: "channels", surface: "channels-private", state: "busy", expectedSurface: "channels-page" },
  { id: "channels-public-initial", journey: "channels", surface: "channels-public", state: "initial", expectedSurface: "channels-page" },
  { id: "channels-public-populated", journey: "channels", surface: "channels-public", state: "populated", expectedSurface: "channels-page" },
  { id: "channels-public-error", journey: "channels", surface: "channels-public", state: "error", expectedSurface: "channels-page" },
  { id: "channel-empty", journey: "channels", surface: "channel", state: "empty", expectedSurface: "channels-page" },
  { id: "channel-populated", journey: "channels", surface: "channel", state: "populated", expectedSurface: "channels-page" },
  { id: "channel-loading", journey: "channels", surface: "channel", state: "loading", expectedSurface: "channels-page" },
  { id: "channel-error", journey: "channels", surface: "channel", state: "error", expectedSurface: "channels-page" },
  { id: "channel-members-open", journey: "channels", surface: "channel", state: "members-open", expectedSurface: "channels-page" },
  { id: "channel-members-non-admin", journey: "channels", surface: "channel", state: "members-non-admin", expectedSurface: "channels-page" },
  { id: "channel-composer-disabled", journey: "channels", surface: "channel", state: "composer-disabled", expectedSurface: "channels-page" },
  { id: "channel-editing", journey: "channels", surface: "channel", state: "editing", expectedSurface: "channels-page" },
  { id: "public-topic-empty", journey: "channels", surface: "public-topic", state: "empty", expectedSurface: "channels-page" },
  { id: "public-topic-populated", journey: "channels", surface: "public-topic", state: "populated", expectedSurface: "channels-page" },
  { id: "public-topic-loading", journey: "channels", surface: "public-topic", state: "loading", expectedSurface: "channels-page" },
  { id: "public-topic-error", journey: "channels", surface: "public-topic", state: "error", expectedSurface: "channels-page" },
  { id: "public-topic-unavailable", journey: "channels", surface: "public-topic", state: "unavailable", expectedSurface: "channels-page" },
  { id: "contacts-empty", journey: "contacts", surface: "contacts", state: "empty", expectedSurface: "contacts-page" },
  { id: "contacts-follows-consent", journey: "contacts", surface: "contacts", state: "follows-consent", expectedSurface: "contacts-page" },
  { id: "contacts-search-results", journey: "contacts", surface: "contacts", state: "search-results", expectedSurface: "contacts-page" },
  { id: "contacts-populated", journey: "contacts", surface: "contacts", state: "populated", expectedSurface: "contacts-page" },
  { id: "contacts-scan-unsupported", journey: "contacts", surface: "contacts-scan", state: "unsupported", expectedSurface: "contact-scanner" },
  { id: "contacts-scan-denied", journey: "contacts", surface: "contacts-scan", state: "denied", expectedSurface: "contact-scanner" },
  { id: "contact-detail-trust", journey: "contacts", surface: "contact-detail", state: "trust", expectedSurface: "contact-detail" },
  { id: "contact-detail-not-found", journey: "contacts", surface: "contact-detail", state: "not-found", expectedSurface: "contact-detail" },
  { id: "profile-not-connected", journey: "profile", surface: "profile", state: "not-connected", expectedSurface: "profile-page" },
  { id: "profile-enabled", journey: "profile", surface: "profile", state: "enabled", expectedSurface: "profile-page" },
  { id: "profile-qr", journey: "profile", surface: "profile-qr", state: "open", expectedSurface: "profile-qr-sheet" },
  { id: "profile-sign-out", journey: "profile", surface: "sign-out", state: "confirm", expectedSurface: "sign-out-confirm" },
  { id: "profile-sign-out-busy", journey: "profile", surface: "sign-out", state: "busy", expectedSurface: "sign-out-confirm" },
  { id: "settings-default", journey: "settings", surface: "settings", state: "default", expectedSurface: "settings-page" },
  { id: "settings-recovery-gate", journey: "settings", surface: "settings", state: "recovery-gate", expectedSurface: "settings-page" },
  { id: "settings-recovery-ready", journey: "settings", surface: "settings", state: "recovery-ready", expectedSurface: "settings-page" },
  { id: "settings-restore-success", journey: "settings", surface: "settings", state: "restore-success", expectedSurface: "settings-page" },
  { id: "settings-error", journey: "settings", surface: "settings", state: "error", expectedSurface: "settings-page" },
  { id: "composer-menu", journey: "composer", surface: "composer-menu", state: "open", expectedSurface: "attachment-menu" },
  { id: "composer-emoji", journey: "composer", surface: "composer-emoji", state: "open", expectedSurface: "emoji-picker" },
  { id: "composer-gif-unconfigured", journey: "composer", surface: "composer-gif", state: "unconfigured", expectedSurface: "composer" },
  { id: "composer-quote", journey: "composer", surface: "composer-quote", state: "reply", expectedSurface: "composer" },
  { id: "thread-day-separators", journey: "chats", surface: "thread", state: "day-separators", expectedSurface: "thread-view" },
  { id: "thread-markdown", journey: "chats", surface: "thread", state: "markdown", expectedSurface: "thread-view" },
  { id: "chats-nickname", journey: "chats", surface: "chats-list", state: "nickname", expectedSurface: "chats-page" },
  { id: "chats-archived", journey: "chats", surface: "chats-list", state: "archived", expectedSurface: "chats-page" },
  { id: "attachment-failed", journey: "composer", surface: "attachment", state: "failed", expectedSurface: "attachment-bubble" },
  { id: "attachment-unavailable", journey: "composer", surface: "attachment", state: "unavailable", expectedSurface: "attachment-bubble" },
  { id: "thread-tagged", journey: "chats", surface: "thread", state: "tagged", expectedSurface: "thread-view" },
  { id: "thread-tag-picker", journey: "chats", surface: "tag-picker", state: "open", expectedSurface: "tag-picker" },
  { id: "thread-receipt-states", journey: "chats", surface: "thread", state: "receipt-states", expectedSurface: "thread-view" },
] as const;

export function findUxCatalogScene(id: string | null): UxCatalogScene {
  return UX_CATALOG_SCENES.find((scene) => scene.id === id) ?? UX_CATALOG_SCENES[0];
}
